### ISSUE TITLE
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#16] opened 2024-01-12 02:06 UTC
```
❯ npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 391 packages, and audited 392 packages in 7s
```

**Comment by abukharov** [comment] 2024-01-17 01:20
Duplicate of https://github.com/Innablr/revolver/issues/17

**Closed by abukharov** 2024-01-17 01:20 UTC
